
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const ActivityLogs = lazy(() => import("./pages/ActivityLogs.tsx"));
const AddClient = lazy(() => import("./pages/AddClient.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const ClientDetail = lazy(() => import("./pages/ClientDetail.tsx"));
const Clients = lazy(() => import("./pages/Clients.tsx"));
const CoachAssistant = lazy(() => import("./pages/CoachAssistant.tsx"));
const ComponentShowcase = lazy(() => import("./pages/ComponentShowcase.tsx"));
const CreateNutritionPlan = lazy(() => import("./pages/CreateNutritionPlan.tsx"));
const CreateProgram = lazy(() => import("./pages/CreateProgram.tsx"));
const CreateTrainingProgram = lazy(() => import("./pages/CreateTrainingProgram.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const DatabaseSetup = lazy(() => import("./pages/DatabaseSetup.tsx"));
const DesignSystem = lazy(() => import("./pages/DesignSystem.tsx"));
const EditClient = lazy(() => import("./pages/EditClient.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const MCP = lazy(() => import("./pages/MCP.tsx"));
const MCPActivation = lazy(() => import("./pages/MCPActivation.tsx"));
const MCPStatus = lazy(() => import("./pages/MCPStatus.tsx"));
const MacroCalculatorPage = lazy(() => import("./pages/MacroCalculatorPage.tsx"));
const MessageTemplates = lazy(() => import("./pages/MessageTemplates.tsx"));
const Notifications = lazy(() => import("./pages/Notifications.tsx"));
const NotificationsDemo = lazy(() => import("./pages/NotificationsDemo.tsx"));
const NutritionPlans = lazy(() => import("./pages/NutritionPlans.tsx"));
const ProgramEditor = lazy(() => import("./pages/ProgramEditor.tsx"));
const Progress = lazy(() => import("./pages/Progress.tsx"));
const ProgressComparisonPage = lazy(() => import("./pages/ProgressComparisonPage.tsx"));
const Signup = lazy(() => import("./pages/Signup.tsx"));
const TrainingPrograms = lazy(() => import("./pages/TrainingPrograms.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/activity-logs", element: <ActivityLogs />},
	{ path: "/activitylogs", element: <ActivityLogs />},
	{ path: "/add-client", element: <AddClient />},
	{ path: "/addclient", element: <AddClient />},
	{ path: "/", element: <App />},
	{ path: "/client-detail", element: <ClientDetail />},
	{ path: "/clientdetail", element: <ClientDetail />},
	{ path: "/clients", element: <Clients />},
	{ path: "/coach-assistant", element: <CoachAssistant />},
	{ path: "/coachassistant", element: <CoachAssistant />},
	{ path: "/component-showcase", element: <ComponentShowcase />},
	{ path: "/componentshowcase", element: <ComponentShowcase />},
	{ path: "/create-nutrition-plan", element: <CreateNutritionPlan />},
	{ path: "/createnutritionplan", element: <CreateNutritionPlan />},
	{ path: "/create-program", element: <CreateProgram />},
	{ path: "/createprogram", element: <CreateProgram />},
	{ path: "/create-training-program", element: <CreateTrainingProgram />},
	{ path: "/createtrainingprogram", element: <CreateTrainingProgram />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/database-setup", element: <DatabaseSetup />},
	{ path: "/databasesetup", element: <DatabaseSetup />},
	{ path: "/design-system", element: <DesignSystem />},
	{ path: "/designsystem", element: <DesignSystem />},
	{ path: "/edit-client", element: <EditClient />},
	{ path: "/editclient", element: <EditClient />},
	{ path: "/login", element: <Login />},
	{ path: "/mcp", element: <MCP />},
	{ path: "/mcp-activation", element: <MCPActivation />},
	{ path: "/mcpactivation", element: <MCPActivation />},
	{ path: "/mcp-status", element: <MCPStatus />},
	{ path: "/mcpstatus", element: <MCPStatus />},
	{ path: "/macro-calculator-page", element: <MacroCalculatorPage />},
	{ path: "/macrocalculatorpage", element: <MacroCalculatorPage />},
	{ path: "/message-templates", element: <MessageTemplates />},
	{ path: "/messagetemplates", element: <MessageTemplates />},
	{ path: "/notifications", element: <Notifications />},
	{ path: "/notifications-demo", element: <NotificationsDemo />},
	{ path: "/notificationsdemo", element: <NotificationsDemo />},
	{ path: "/nutrition-plans", element: <NutritionPlans />},
	{ path: "/nutritionplans", element: <NutritionPlans />},
	{ path: "/program-editor", element: <ProgramEditor />},
	{ path: "/programeditor", element: <ProgramEditor />},
	{ path: "/progress", element: <Progress />},
	{ path: "/progress-comparison-page", element: <ProgressComparisonPage />},
	{ path: "/progresscomparisonpage", element: <ProgressComparisonPage />},
	{ path: "/signup", element: <Signup />},
	{ path: "/training-programs", element: <TrainingPrograms />},
	{ path: "/trainingprograms", element: <TrainingPrograms />},

];
