name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'  # Weekly Monday 6 AM UTC

jobs:
  secrets-scan:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for secret scanning
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified

  backend-security:
    name: Backend Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install security tools
        run: |
          pip install bandit safety
      
      - name: Run Bandit
        run: |
          bandit -r backend/ -f json -o bandit-report.json || true
          bandit -r backend/ -ll
        continue-on-error: true
      
      - name: Run Safety
        run: |
          safety check --file backend/requirements.txt
        continue-on-error: true
      
      - name: Upload Bandit results
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.json

  frontend-security:
    name: Frontend Security Scan  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Run npm audit
        working-directory: frontend
        run: |
          npm audit --audit-level moderate || true
          npm audit --json > npm-audit-report.json || true
        continue-on-error: true
      
      - name: Upload npm audit results
        uses: actions/upload-artifact@v3
        with:
          name: npm-audit-report
          path: frontend/npm-audit-report.json

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [secrets-scan, backend-security, frontend-security]
    if: always()
    steps:
      - name: Security Check Summary
        run: |
          echo "## 🔒 Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Secrets scan: ${{ needs.secrets-scan.result }}" >> $GITHUB_STEP_SUMMARY  
          echo "- Backend security: ${{ needs.backend-security.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Frontend security: ${{ needs.frontend-security.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📊 View detailed reports in job artifacts" >> $GITHUB_STEP_SUMMARY